### ISSUE TITLE
Unknown controller error using T.Flight Hotas One on PC

### ISSUE THREAD

**Issue by richardbuckle** [richardbuckle/EDRefCard#17]
https://edrefcard.info/binds/etomni
https://forums.frontier.co.uk/showthread.php/212866-Keyboard-and-HOTAS-Reference-Sheet-Generator?p=6388530&viewfull=1#post6388530

**Comment by rpgrunwald** [comment]
There is a binds file in the repository for this,  what needs to happen to get this working?  How can I help?

**Comment by richardbuckle** [comment]
This is a dead issue I think.

**Comment by rpgrunwald** [comment]
It's not working on [edrefcard.info ](https://edrefcard.info/) for me and apparently others - https://forums.frontier.co.uk/search/764228/?q=t.flight+one&t=post&c[thread]=464400&o=relevance

**Comment by richardbuckle** [comment]
All of those reports are over two years old. Please note that the official site is [edrefcard.info](https://edrefcard.info), not .com. I have edited your comment to correct this potentially misleading error.

The files in the repo are those that ship with the game. I cannot provide support for the game.

**Comment by rpgrunwald** [comment]
The TFlightHOTASX is supported.  The  TFlightHOTASOne is not.  They are nearly identical hardware.  What needed to be done to add that support and can I help?

**Comment by richardbuckle** [comment]
We need to distinguish between in-game support and support for displaying a nice reference card on this third-party website.

First you need to determine the PID (product ID) and VID (vendor ID) for your TFlightHOTASOne. This [post](https://superuser.com/questions/1106247/how-can-i-get-the-vendor-id-and-product-id-for-a-usb-device) shows how.

This [reddit post](https://www.reddit.com/r/Mechwarrior5/comments/evzy5r/thrustmaster_t_flight_hotas_issues/) indicates VID: 0x044F and PID: 0xB67C. 

For in-game support you need to petition FDev to add support by listing the device's PID and VID in `DeviceMappings.xml`. 

I can only help with the latter. If the TFlightHOTASOne is an alias for the TFlightHOTASX then be added using the given PID and VID after you have confirmed that they are correct.

**Comment by rpgrunwald** [comment]
This is from USBDeview and it shows Device b68d, vender 044f
![image](https://github.com/richardbuckle/EDRefCard/assets/26696561/b11eb685-f09b-4e7b-9520-7760c3b6a903)

As I understand it, there are three similar devices but they are not identical, close, but not identical.   It would not be an alias.  

The stick and throttle handle  buttons are the same on all,  The stick base is plain on the X and 4. the One has control buttons for X box mode (11 & 12) (and hard switch) the Logo button is not .   Throttle is the same from the X and 4, just labeled differently.  I only have the One so I can't confirm 100%. 


T.Flight HOTAS X    PC and PS3  https://www.thrustmaster.com/en-us/products/t-flight-hotas-x/  
T.Flight HOTAS 4 works on PS4/5 and PC   https://www.thrustmaster.com/en-us/products/t-flight-hotas-4/
T.Flight HOTAS One works on XBox and PC    https://www.thrustmaster.com/en-us/products/t-flight-hotas-one/
