### ISSUE TITLE
Running on DreamHost with default Python 2.7.6

### ISSUE THREAD

**Issue by Slion** [richardbuckle/EDRefCard#21]
I got it working on DreamHost with the default Python 2.7.6 but it was quite a bit of work.
I have to mention that I had managed to hardly ever touch a Python script before in 20+ years of software engineering. I'm more of a Perl guy. Doing the backport from 3.x to 2.x was rather funny.
I'm not sure if you are interested in getting those changes merged back here, nor if it will still run on 3.x.

I'll try clone and push the changes later today.

**Comment by Slion** [comment]
I've pushed those changes there:
https://github.com/Slion/EDRefCard/tree/DreamHost

**Comment by Slion** [comment]
Here is a quick reference of the pages that helped me deal with DreamHost issues:
https://help.dreamhost.com/hc/en-us/articles/115000221112-Using-pip-to-install-Python-2-modules
https://help.dreamhost.com/hc/en-us/articles/215489338-Installing-and-using-virtualenv-with-Python-2
To force encoding to utf-8 using env variable:
https://help.dreamhost.com/hc/en-us/articles/215364578-How-do-I-use-suEXEC-

**Comment by richardbuckle** [comment]
We will not be downgrading to an obsolete version of Python.
