### ISSUE TITLE
Lacks Thrustmaster Cougar Hotas support

### ISSUE THREAD

**Issue by richardbuckle** [richardbuckle/EDRefCard#23]
Hello I have problem with Thrustmaster Cougar Hotas, which I only have the stick (original throttle is missing from my set) which shows up as device: 044F0400

If I replace "044F0400" with "ThrustMasterWarthogJoystick" in the config file, I can get configs mapped on warthog stick which seems to be identical with this Cougar one.

[Forum post](https://forums.frontier.co.uk/showthread.php/212866-Keyboard-and-HOTAS-Reference-Sheet-Generator?p=7048711&viewfull=1#post7048711).
[New format forum post](https://forums.frontier.co.uk/threads/keyboard-and-hotas-reference-sheet-generator.212866/post-3715865).

**Comment by grue74** [comment]
[.afdesign layout file](http://sid.fi/~grue/Thrustmaster%20Cougar%20and%20CH%20Throttle.afdesign)

[.jpg layout](http://sid.fi/~grue/Thrustmaster%20Cougar%20and%20CH%20Throttle.jpg)

**Comment by grue74** [comment]
I added support, here is modified bindingsdata.py and .jpg
http://sid.fi/~grue/hotascougar.zip

**Comment by richardbuckle** [comment]
Thanks @grue74! I have made a branch `23-cougar` for the finishing touches and have switched the beta server over to it for the time being. As you will see from https://beta.edrefcard.info/device/HotasCougar, some of the rectangles need minor tweaks. Also, please could you add the vector graphics source to the `Reference sheets` folder in that branch (or attach it here). It doesn't have to be afdesign, any mainstream vector format is fine.

If you could also please check that the button map labels are correct that would be great!

**Comment by grue74** [comment]
Here you can get .afdesign file for cougar. I'll modify those boxes when I have bit more time on my hands :)
http://sid.fi/~grue/ThrustMaster_Cougar.afdesign

**Comment by richardbuckle** [comment]
Sample binds file
[gyrprb.binds.txt](https://github.com/richardbuckle/EDRefCard/files/4182927/gyrprb.binds.txt)

**Comment by richardbuckle** [comment]
> Here you can get .afdesign file for cougar. I'll modify those boxes when I have bit more time on my hands :)
> http://sid.fi/~grue/ThrustMaster_Cougar.afdesign

Thanks for the fast response! I should be able to revise the co-ordinates from that -- it's so much easier to get co-ordinates from a vector file :)

**Comment by richardbuckle** [comment]
Boxes tweaked at https://beta.edrefcard.info/device/HotasCougar (you may need to force-reload with shift-F5, ctrl+shift+R, or cmd+opt+R on Mac).

Sample binds from the original post at https://beta.edrefcard.info/binds/bfsyly

Please test away. On getting home tomorrow I'll update the change log and push to production.

Many thanks for the contribution.

**Comment by richardbuckle** [comment]
Fixed on release 1.2.7.
