### ISSUE TITLE
ExplorationFSSRadioTuningAbsoluteX

### ISSUE THREAD

**Issue by lwt-pressy** [richardbuckle/EDRefCard#28]
With the latest beta release (week 3) there is a new setting added for fss: ExplorationFSSRadioTuningAbsoluteX. 

e.g.

	<ExplorationFSSRadioTuningAbsoluteX>
		<Binding Device="SaitekX56Throttle" Key="Joy_VAxis" />
		<Inverted Value="0" />
		<Deadzone Value="0.00000000" />
	</ExplorationFSSRadioTuningAbsoluteX>

**Comment by richardbuckle** [comment]
Also new SAA bindings https://beta.edrefcard.info/binds/vadvwv

**Comment by lwt-pressy** [comment]
thx, works in the beta
