### ISSUE TITLE
Feature request: Searchability

### ISSUE THREAD

**Issue by treyharris** [richardbuckle/EDRefCard#33]
I often use my EDRefCard to try to find my binding for a certain feature, either
1. Because I don't remember what section of Options → Controls the particular control is, or
2. Because the game doesn't have a friendly display for the button involved, and I don't know where `JOY29` or whatever is.

It's also often a somewhat frantic search because I'm actually _playing_ when I realize I can't remember how to send a certain command without rebinding it.

So: a way to search the ref card would be _great._ I can think of at least two ways:
1. Use SVG to draw the box elements so that the text is searchable in the browser right on the diagram
1. Have a separate section (toggle-able in the main interface, I assume) that lists the bindings in text table form, so that at least if I search for something on `JOY29`, one of the other things on that button might jog my memory as to where it is.

Thanks, it's a great tool!

**Comment by richardbuckle** [comment]
Ref #51 we will convert to SVG
