### ISSUE TITLE
[T16000MFCS][ZAxis] Recognition on the Joystick is incorrect for key binds

### ISSUE THREAD

**Issue by ghost** [richardbuckle/EDRefCard#37]
Hi,

first off: Amazing project, loving this!

My issue: According to the 'default' card here: https://edrefcard.info/device/T16000MFCS you are working under the assumption that 'RZAxis' is the 'twist' axis on the Joystick.

My config would like to somewhat disagree with you on that. ;)

On my Joystick I mapped the (R)ZAxis to cycling the subsystems of my target, this is my config:

```	
<CycleNextSubsystem>
		<Primary Device="T16000M" Key="Neg_Joy_ZAxis" />
		<Secondary Device="{NoDevice}" Key="" />
	</CycleNextSubsystem>
	<CyclePreviousSubsystem>
		<Primary Device="T16000M" Key="Pos_Joy_ZAxis" />
		<Secondary Device="{NoDevice}" Key="" />
	</CyclePreviousSubsystem>
```

For non-key inputs the same axis is recognized as 'RZAxis' as seen here

```
	<CommanderCreator_Rotation>
		<Binding Device="T16000M" Key="Joy_RZAxis" />
		<Inverted Value="1" />
		<Deadzone Value="0.00000000" />
	</CommanderCreator_Rotation>
```

The generated card looks like this: 
![adgvpu-t16000mfcs](https://user-images.githubusercontent.com/46234045/65171930-4ca8a080-da4c-11e9-90da-c550751a2ede.jpg)

**Comment by richardbuckle** [comment]
Thank you for the report: I'm sorry that I did not see it sooner.

First off, I am not working under any assumptions. I own the TWCS and have verified for myself, using `joy.cpl` and in game, that the axes and buttons are as shown in https://edrefcard.info/device/T16000MFCS.

I have just hand-edited all my `Joy_RZAxis` bindings on the stick to `Joy_ZAxis` and my `Joy_UAxis` binding on the throttle to `Joy_VAxis` and tested them in-game: as expected they were unresponsive. 

When I set the twist axis on the stick to cycle subsystems, I got:

```xml
	<CycleNextSubsystem>
		<Primary Device="T16000M" Key="Joy_POV1Up" />
		<Secondary Device="T16000M" Key="Pos_Joy_RZAxis" />
	</CycleNextSubsystem>
	<CyclePreviousSubsystem>
		<Primary Device="T16000M" Key="Joy_POV1Down" />
		<Secondary Device="T16000M" Key="Neg_Joy_RZAxis" />
	</CyclePreviousSubsystem>
```

So I'm at a loss to explain your results. Are you perhaps running any middleware such as TARGET or Joystick Curves that could have re-mapped the axes?

**Comment by ghost** [comment]
oh that is interesting. I'm on Linux. Personally, interesting to see that the enumeration of the axis depends on the driver implementation, never really thought about it.

I guess that means I have to dig deeper into driver stuff and/or file an issue report with driver developers. Thanks & Sorry for barking up the wrong tree!
