### ISSUE TITLE
[T16000MFCS][V/UAxis] Recognition on the Thruster is incorrect

### ISSUE THREAD

**Issue by ghost** [richardbuckle/EDRefCard#38]
On the Thruster, I have the wheel mapped to zooming the radar

```
	<RadarRangeAxis>
		<Binding Device="T16000MTHROTTLE" Key="Joy_VAxis" />
		<Inverted Value="1" />
		<Deadzone Value="0.00000000" />
	</RadarRangeAxis>
```

According to the reference card, you believe this to be the UAxis. This is the default config provided by the game, I didn't touch that part and it is working.

Generated card shows nothing is mapped to the wheel.

![adgvpu-t16000mfcs](https://user-images.githubusercontent.com/46234045/65171930-4ca8a080-da4c-11e9-90da-c550751a2ede.jpg)

**Comment by richardbuckle** [comment]
See comments to #37.

**Comment by ghost** [comment]
oh that is interesting. I'm on Linux. Personally, interesting to see that the enumeration of the axis depends on the driver implementation, never really thought about it.

I guess that means I have to dig deeper into driver stuff and/or file an issue report with driver developers. Thanks & Sorry for barking up the wrong tree!
