### ISSUE TITLE
List Search

### ISSUE THREAD

**Issue by LiruMouse** [richardbuckle/EDRefCard#39]
I couldn't wait, so I wrote a userscript for searching EdRefCard's list page. It's a very basic search for a "very basic" page, but hopefully it helps more people than just me. (Heck, maybe you can make use of it in lieu of a real search)

```js
// ==UserScript==
// @name         EDRefCard Search
// @version      0.1
// @author       Liru Færs
// @match        *edrefcard.info/list*
// ==/UserScript==

document.addEventListener('keydown', function(e) {
    if (e.keyCode != 191) return;
    let search = prompt("Search for what?");
    for (let tr of document.getElementsByTagName('tr')) {
        tr.style.display = !search || tr.innerHTML.includes(search) ? "block" : "none";
    }
});
```

Simple how to use for those that can't read code:
Copy paste and save this as a new userscript in TamperMonkey/GreaseMonkey, refresh the list page to activate the script. Then navigate to the edrefcard list page.
Press ? or / to bring up a prompt for what to search for.
Type in what you want to search for (it is case sensitive).
To search for something else just press the key to bring up the prompt again.
To clear the search and show everything again just type nothing in the search prompt.

Anyway use it, don't use it, tear it apart, I leave it here for free use.

**Comment by richardbuckle** [comment]
Superseded by #48
