### ISSUE TITLE
https://edrefcard.info can’t be reached

### ISSUE THREAD

**Issue by dylan-k** [richardbuckle/EDRefCard#54]
Is the site down? It says ``ERR_CONNECTION_TIMED_OUT``.

**Comment by hplato** [comment]
Fire in the datacentre, there's a thread on frontier about it. Hopefully the snapshot can be recovered.

**Comment by dylan-k** [comment]
oh sad news! fwiw I did see some info saved via the wayback machine @ archive.org

...hope so too that everything can be recovered ok.

**Comment by richardbuckle** [comment]
Yes, I am looking at options to rebuild the server. The snapshot is lost unfortunately.

**Comment by jeffstokes72** [comment]
Hey @richardbuckle I wrote that blog post on standing up a docker instance, I was entertaining putting it in AWS or Az and making it publicly available. Is that ok or are you doing that?
  Figure we could S3bucket or Azure blob store the configs

**Comment by richardbuckle** [comment]
Since OVH are compensating me with a decent period of free hosting, I am planning to spin the server back up there over the Easter weekend.

**Comment by jeffstokes72** [comment]
> Since OVH are compensating me with a decent period of free hosting, I am planning to spin the server back up there over the Easter weekend.

You want to coordinate a replication to Azure storage or AWS? I got that free 150/mo deal going on.

**Comment by richardbuckle** [comment]
Hardware is back up and I am working on a reinstall.

**Comment by ritchiedalto** [comment]
I'm getting a 503 at https://edrefcard.info/. No luck getting it running again? Do you need a donation or a server to run on? I would help. I'm just getting back into E:D after many years and I SOOOO need this tool my friend :)

**Comment by dylan-k** [comment]
I think that the work is ongoing but meanwhile there is a community fork at
http://edrefcard.slions.net/
It's not as up-to-date but it might help in a pinch.

**Comment by ritchiedalto** [comment]
> I think that the work is ongoing but meanwhile there is a community fork at http://edrefcard.slions.net/ It's not as up-to-date but it might help in a pinch.

OMG Thank you kindly. This will GREATLY improve my sanity.

**Comment by jeffstokes72** [comment]
You can also run your own docker instance. https://illuminati.services/2021/03/31/edrefcard-info-is-down-long-live-edrefcard-how-to-set-up-your-own-instance-of-edrefcard-so-you-can-create-a-card-for-your-hotas-config-in-elite-dangerous/

**Comment by dylan-k** [comment]
I've never run a Docker instance before but I think I could manage it. Are
there any good, general how-tos out there that you would recommend? Maybe I
could write down the steps I take and share them for this project's
documentation?

**Comment by jeffstokes72** [comment]
My blog post describes it, at least the docker desktop in Windows how-to. Its my understanding that for linux/headless, you’d just get docker installed then run the command. 

 

docker run -d --rm --name edrefcard -p 8080:80 jeffstokes72/edrefcard

**Comment by jeffstokes72** [comment]
Also stood it up in Azure, http://52.255.223.220/

Mainly to learn how docker in azure worked as an exercise.

I don't know what the project owner needs. I offered to help make it highly available but he never replied. Shrug.

**Comment by richardbuckle** [comment]
The site is now back up.

**Comment by richardbuckle** [comment]
I do appreciate the community effort to provide workarounds and spin them up. And I do realise that it has been a big outage.

I happy to announce that as of now, the primary site is back up.

OVH have provided me three years of free hosting as compensation, so my approach is now to utilise that while reviewing my options.

Now that I have got everything back up and running nicely on the primary host, please can we stand down the backups that you have so kindly spun up?

Thanks and regards!

**Comment by jeffstokes72** [comment]
Hi, I've honored your request.

I've taken down the Azure docker node I had up, and made a note on my blog property to the effect it is no longer needed.
