### ISSUE TITLE
Support for Steam Controller

### ISSUE THREAD

**Issue by dylan-k** [richardbuckle/EDRefCard#60]
Tested an upload using the new `.4.0` format for bindings file, and also one that I made for the Steam Controller. It seems EDRefCard doesn't have support for that controller; I got an error. "The error also suggested supplying the reference `qyrnxs` and we will attempt to add support for it."

Would it be possible to add support for the steam controller?

**Comment by sircompo** [comment]
I'll second that. I don't use the controller for flying, but it's great for SRV control.

I think the Steam controller comes up with various device IDs depending on its mode of operation.
If it's emulating a 360 pad, it'll show up as VID: 28DE, PID: 11FF
But I think it's possible for other modes to come up as one of -
- 28de:1102  
- 28de:1105  
- 28de:1106  
- 28de:1142  
- 28de:11fc  
- 28de:1201  
- 28de:1202
