### ISSUE TITLE
edrefcard.info domain expired?

### ISSUE THREAD

**Issue by SirWumpus** [richardbuckle/EDRefCard#79]
It appears that `https://edrefcard.info` has expired.  Is there an alternative domain for this?

**Comment by hansen12193** [comment]
+1

**Comment by richardbuckle** [comment]
I have retired and transferred the site to new maintainers: [forum link](https://forums.frontier.co.uk/threads/edrefcard-v1-4-new-hosting-new-maintainers-the-follow-on-to-edrefcard-makes-a-printable-reference-card-of-your-controller-bindings.627609/)

They have a snapshot of the old site and can restore any config from it: this has been tested.


DNS updates should now have propagated. If not , please re-open
